const docs=[{ref:"REF-DEMO-042",title:"Note de synthèse — Projet Démo",type:"Note",status:"En validation",date:"25 août 2026"},{ref:"REF-DEMO-041",title:"Compte rendu — Réunion fictive",type:"Compte rendu",status:"Approuvé",date:"24 août 2026"},{ref:"REF-DEMO-040",title:"Rapport mensuel — Exemple",type:"Rapport",status:"Brouillon",date:"18 août 2026"},{ref:"REF-DEMO-039",title:"Note interne — Cas simulé",type:"Note",status:"Approuvé",date:"12 août 2026"}];
const views=document.querySelectorAll(".view"),nav=document.querySelectorAll(".nav"),side=document.querySelector(".shell>aside");
function show(id){views.forEach(x=>x.classList.toggle("active",x.id===id));nav.forEach(x=>x.classList.toggle("active",x.dataset.view===id));side.classList.remove("open");scrollTo({top:0,behavior:"smooth"})}nav.forEach(x=>x.onclick=()=>show(x.dataset.view));document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>show(x.dataset.go));document.querySelector("#menu").onclick=()=>side.classList.toggle("open");
function row(d){const c=d.status==="Approuvé"?"ok":d.status==="Brouillon"?"draft":"";return `<div class="doc"><i>${d.type[0]}</i><div><b>${d.title}</b><small>${d.ref}</small></div><span>${d.date}</span><em class="badge ${c}">${d.status}</em></div>`}let filter="all";function render(q=""){q=q.toLocaleLowerCase("fr");document.querySelector("#recent").innerHTML=docs.slice(0,3).map(row).join("");const result=docs.filter(d=>(filter==="all"||d.status===filter)&&`${d.title} ${d.ref}`.toLocaleLowerCase("fr").includes(q));document.querySelector("#doc-table").innerHTML=result.length?result.map(row).join(""):"<p>Aucun exemple trouvé.</p>"}render();
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render(document.querySelector("#doc-search").value)});document.querySelector("#doc-search").oninput=e=>render(e.target.value);
const replies={note:"Structure fictive proposée :\n1. Contexte de démonstration\n2. Objectif simulé\n3. Analyse illustrative\n4. Proposition générique\n5. Prochaines étapes",compte:"Compte rendu fictif : participants génériques, ordre du jour, décisions simulées et actions de démonstration.",rapport:"Plan fictif : synthèse, périmètre, indicateurs de démonstration, analyse, recommandations génériques et conclusion.",other:"Cette démonstration propose uniquement des structures génériques. Aucun service externe n’est appelé et votre texte n’est pas conservé."};
function message(text,role){const x=document.createElement("div");x.className=`message ${role}`;x.innerHTML=`<i>${role==="user"?"UD":"✦"}</i><p></p>`;x.querySelector("p").textContent=text;document.querySelector("#messages").append(x)}function ask(key,text){message(text,"user");setTimeout(()=>message(replies[key]||replies.other,"bot"),300)}document.querySelectorAll("[data-prompt]").forEach(b=>b.onclick=()=>ask(b.dataset.prompt,b.textContent));document.querySelector("#chat-form").onsubmit=e=>{e.preventDefault();const i=document.querySelector("#chat-input"),v=i.value.trim();if(v){i.value="";ask("other",v)}};
let step=2;document.querySelector("#advance").onclick=()=>{step=step===4?1:step+1;const labels=["Rédaction","Révision","Validation","Publication"];document.querySelectorAll(".step").forEach((x,i)=>{x.classList.toggle("done",i+1<step);x.classList.toggle("current",i+1===step);x.querySelector("i").textContent=i+1<step?"✓":i+1;x.querySelector("span").textContent=i+1<step?"Terminée":i+1===step?"Étape actuelle":"En attente"});document.querySelectorAll(".steps hr").forEach((x,i)=>x.classList.toggle("done",i+1<step));document.querySelector("#status").textContent=step===4?"Prêt à publier":"En validation";document.querySelector("#workflow-note").textContent=`La simulation est positionnée sur l’étape « ${labels[step-1]} ».`};
const dialog=document.querySelector("dialog");document.querySelectorAll(".create").forEach(b=>b.onclick=()=>dialog.showModal());document.querySelector("#close").onclick=()=>dialog.close();document.querySelector("#create-form").onsubmit=e=>{e.preventDefault();const title=document.querySelector("#new-title").value.trim(),type=document.querySelector("#new-type").value;if(!title)return;docs.unshift({ref:`REF-DEMO-${43+docs.length}`,title:`${type} — ${title}`,type,status:"Brouillon",date:"25 août 2026"});render();dialog.close();e.target.reset();show("documents");const t=document.querySelector("#toast");t.textContent="Brouillon fictif créé localement.";t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)};
